version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        environment:
          BUNDLE_PATH: vendor/bundle
          TERRAFORM_VERSION: 0.11.11

    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - terraform-aws-vpc-{{ checksum "Gemfile.lock" }}
            - terraform-aws-vpc-

      # Install test dependencies
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      
      - save_cache:
          key: terraform-aws-vpc-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      
      - run:
          name: Install terraform
          command: |
            curl -o terraform.zip https://releases.hashicorp.com/terraform/{{$TERRAFORM_VERSION}}/terraform_{{$TERRAFORM_VERSION}}_linux_amd64.zip &&
            unzip terraform.zip && chmod +x terraform && mv terraform /usr/local/bin

      - run:
          name: Run kitchen test
          command: bundle exec kitchen test
